# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('available', 'Avaliable'), ('unavailable', 'Unavailable')], max_length=100)),
                ('check_interval', models.PositiveIntegerField(help_text='In seconds')),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
