# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_url_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], max_length=100),
        ),
    ]
