# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_auto_20181125_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='check_interval',
        ),
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('error', 'Error')], max_length=100, null=True),
        ),
    ]
